### ISSUE TITLE
[coc.nvim] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received null

### ISSUE THREAD

**Issue by Freed-Wu** [weirongxu/coc-markdown-preview-enhanced#17]
**Describe the bug**

When I use `ImageHelper` to upload picture, this error will occur.

**Result from CocInfo**

```

## versions

vim version: NVIM v0.7.2
node version: v18.8.0
coc.nvim version: 0.0.82-f39f5f69 2022-10-07 23:24:25 +0800
coc.nvim directory: /home/wzy/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release
term: tmux
platform: linux

## Log of coc.nvim

2022-10-18T18:45:17.365 INFO (pid:4086037) [services] - registered service "diagnostic-languageserver"
2022-10-18T18:45:17.375 INFO (pid:4086037) [services] - LanguageClient diagnostic language service state change: stopped => starting
2022-10-18T18:45:17.441 INFO (pid:4086037) [coc-git] - Looking for git in: git
2022-10-18T18:45:17.453 INFO (pid:4086037) [services] - registered service "highlight"
2022-10-18T18:45:17.596 INFO (pid:4086037) [coc-tabnine] - Using tabnine from /home/wzy/.config/coc/extensions/coc-tabnine-data/binaries/4.4.153/x86_64-unknown-linux-musl/TabNine
2022-10-18T18:45:17.990 INFO (pid:4086037) [plugin] - coc.nvim initialized with node: v18.8.0 after 1117ms
2022-10-18T18:45:18.060 WARN (pid:4086037) [workspace] - workspace.createStatusBarItem is deprecated, please use window.createStatusBarItem instead. 
    at t.initStatusBar (/home/wzy/.config/coc/extensions/node_modules/coc-spell-checker/out/index.js:1:155873)
    at t.activate (/home/wzy/.config/coc/extensions/node_modules/coc-spell-checker/out/index.js:1:23099)
2022-10-18T18:45:18.111 INFO (pid:4086037) [services] - LanguageClient highlight server state change: starting => running
2022-10-18T18:45:18.117 INFO (pid:4086037) [services] - LanguageClient diagnostic language service state change: starting => running
2022-10-18T18:45:18.118 INFO (pid:4086037) [services] - service diagnostic-languageserver started
2022-10-18T18:45:20.835 INFO (pid:4086037) [attach] - receive notification: runCommand [ 'markdown-preview-enhanced.openPreview' ]
2022-10-18T18:45:25.179 INFO (pid:4086037) [attach] - receive notification: openList [ 'commands' ]
2022-10-18T18:45:25.216 INFO (pid:4086037) [attach] - receive notification: doAutocmd [ 2 ]
2022-10-18T18:45:27.089 INFO (pid:4086037) [attach] - receive notification: doAutocmd [ 2 ]
2022-10-18T18:45:46.331 INFO (pid:4086037) [attach] - receive notification: showInfo []
```

**Steps to reproduce**
1. execute `nvim`
2. `:CocCommand markdown-preview-enhanced.openPreview`
3. `:CocCommand markdown-preview-enhanced.openImageHelper`
4. Upload a picture
5. See error

**Expected behavior**

Not error.

**Screenshots**

**Additional context**
None

**Comment by weirongxu** [comment]
I just fixed it on coc-webview 0.11.2, please upgrade the coc-webview.
