### ISSUE TITLE
[BUG] Command: markdown-preview-enhanced.openPreview not found

### ISSUE THREAD

**Issue by supremew** [weirongxu/coc-markdown-preview-enhanced#30]
**Describe the bug**

markdown-preview-enhanced.openPreview not found
**Result from CocInfo**

## versions

vim version: VIM - Vi IMproved 9.1 9010330
node version: v22.5.0
coc.nvim version: 0.0.82-33d0a523 2024-07-12 09:31:17 +0800
coc.nvim directory: C:\Users\Mew\vimfiles\plugged\coc.nvim
term: undefined
platform: win32

## Log of coc.nvim

2024-07-21T09:25:58.315 INFO (pid:32392) [extension:coc-git] - Looking for git in: git
2024-07-21T09:25:58.360 INFO (pid:32392) [plugin] - coc.nvim initialized with node: v22.5.0 after 299
2024-07-21T09:25:58.363 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:26:19.047 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:26:31.756 INFO (pid:32392) [attach] - receive notification: updateExtensions []
2024-07-21T09:26:31.793 INFO (pid:32392) [attach] - receive notification: doAutocmd [ 1, 2 ]
2024-07-21T09:26:32.262 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:26:52.108 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:26:52.641 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:26:58.180 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:27:03.754 INFO (pid:32392) [attach] - receive notification: doAutocmd [ 2, 2 ]
2024-07-21T09:27:04.103 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:27:05.489 INFO (pid:32392) [attach] - receive notification: runCommand [ 'explorer' ]
2024-07-21T09:27:05.610 INFO (pid:32392) [attach] - receive notification: doAutocmd [ 1, 4 ]
2024-07-21T09:27:06.138 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:27:08.130 INFO (pid:32392) [attach] - Request action: doKeymap [ 'coc-explorer-key-n-gd' ]
2024-07-21T09:27:08.274 INFO (pid:32392) [attach] - receive notification: openList [ '--normal', '--number-select', 'explorerDrives' ]
2024-07-21T09:27:08.325 INFO (pid:32392) [attach] - receive notification: doAutocmd [ 1, 5 ]
2024-07-21T09:27:11.876 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:27:13.042 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:27:13.703 INFO (pid:32392) [attach] - Request action: doKeymap [ 'coc-explorer-key-n-l' ]
2024-07-21T09:27:14.051 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:27:15.184 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:27:15.757 INFO (pid:32392) [attach] - Request action: doKeymap [ 'coc-explorer-key-n-l' ]
2024-07-21T09:27:16.116 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:27:18.292 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:27:19.367 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:27:19.373 INFO (pid:32392) [attach] - Request action: doKeymap [ 'coc-explorer-key-n-l' ]
2024-07-21T09:27:19.741 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:27:20.609 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:27:21.753 INFO (pid:32392) [attach] - Request action: doKeymap [ 'coc-explorer-key-n-l' ]
2024-07-21T09:27:22.117 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:27:23.097 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:27:23.498 INFO (pid:32392) [attach] - Request action: doKeymap [ 'coc-explorer-key-n-l' ]
2024-07-21T09:27:23.857 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:27:25.240 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:27:27.423 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:27:27.731 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:27:28.866 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:27:28.995 INFO (pid:32392) [attach] - Request action: doKeymap [ 'coc-explorer-key-n-[cr]' ]
2024-07-21T09:27:29.368 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:27:31.815 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:27:34.984 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:27:35.673 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:27:37.413 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:27:39.354 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:27:40.750 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:27:41.682 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:27:45.780 INFO (pid:32392) [attach] - Request action: doKeymap [ 'coc-explorer-key-n-[cr]' ]
2024-07-21T09:27:45.872 INFO (pid:32392) [attach] - receive notification: doAutocmd [ 1, 1 ]
2024-07-21T09:27:45.872 INFO (pid:32392) [attach] - receive notification: doAutocmd [ 2, 1 ]
2024-07-21T09:27:45.991 ERROR (pid:32392) [extensions-manager] - Error on active extension coc-markdown-preview-enhanced: Error: Cannot find module '@shd101wyy/mume'
Require stack:
- C:\Users\Mew\AppData\Local\coc\extensions\node_modules\coc-markdown-preview-enhanced\lib\index.js
- C:\Users\Mew\AppData\Local\coc\extensions\node_modules\coc-markdown-preview-enhanced\lib\index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1219:15)
    at Module._load (node:internal/modules/cjs/loader:1045:27)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:215:24)
    at Module.require (node:internal/modules/cjs/loader:1304:12)
    at req (C:\Users\Mew\vimfiles\plugged\coc.nvim\build\index.js:77984:17)
    at Object.<anonymous> (C:\Users\Mew\AppData\Local\coc\extensions\node_modules\coc-markdown-preview-enhanced\lib\index.js:262:20)
    at Module._compile (C:\Users\Mew\vimfiles\plugged\coc.nvim\build\index.js:78000:28)
    at Module._extensions..js (node:internal/modules/cjs/loader:1588:10)
    at Module.load (node:internal/modules/cjs/loader:1282:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\Mew\\AppData\\Local\\coc\\extensions\\node_modules\\coc-markdown-preview-enhanced\\lib\\index.js',
    'C:\\Users\\Mew\\AppData\\Local\\coc\\extensions\\node_modules\\coc-markdown-preview-enhanced\\lib\\index.js'
  ]
}
2024-07-21T09:27:45.992 ERROR (pid:32392) [server] - unhandledRejection  Promise {
  <rejected> Error: Cannot find module '@shd101wyy/mume'
  Require stack:
  - C:\Users\Mew\AppData\Local\coc\extensions\node_modules\coc-markdown-preview-enhanced\lib\index.js
  - C:\Users\Mew\AppData\Local\coc\extensions\node_modules\coc-markdown-preview-enhanced\lib\index.js
      at Module._resolveFilename (node:internal/modules/cjs/loader:1219:15)
      at Module._load (node:internal/modules/cjs/loader:1045:27)
      at TracingChannel.traceSync (node:diagnostics_channel:315:14)
      at wrapModuleLoad (node:internal/modules/cjs/loader:215:24)
      at Module.require (node:internal/modules/cjs/loader:1304:12)
      at req (C:\Users\Mew\vimfiles\plugged\coc.nvim\build\index.js:77984:17)
      at Object.<anonymous> (C:\Users\Mew\AppData\Local\coc\extensions\node_modules\coc-markdown-preview-enhanced\lib\index.js:262:20)
      at Module._compile (C:\Users\Mew\vimfiles\plugged\coc.nvim\build\index.js:78000:28)
      at Module._extensions..js (node:internal/modules/cjs/loader:1588:10)
      at Module.load (node:internal/modules/cjs/loader:1282:32) {
    code: 'MODULE_NOT_FOUND',
    requireStack: [
      'C:\\Users\\Mew\\AppData\\Local\\coc\\extensions\\node_modules\\coc-markdown-preview-enhanced\\lib\\index.js',
      'C:\\Users\\Mew\\AppData\\Local\\coc\\extensions\\node_modules\\coc-markdown-preview-enhanced\\lib\\index.js'
    ]
  }
} Error: Cannot find module '@shd101wyy/mume'
Require stack:
- C:\Users\Mew\AppData\Local\coc\extensions\node_modules\coc-markdown-preview-enhanced\lib\index.js
- C:\Users\Mew\AppData\Local\coc\extensions\node_modules\coc-markdown-preview-enhanced\lib\index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1219:15)
    at Module._load (node:internal/modules/cjs/loader:1045:27)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:215:24)
    at Module.require (node:internal/modules/cjs/loader:1304:12)
    at req (C:\Users\Mew\vimfiles\plugged\coc.nvim\build\index.js:77984:17)
    at Object.<anonymous> (C:\Users\Mew\AppData\Local\coc\extensions\node_modules\coc-markdown-preview-enhanced\lib\index.js:262:20)
    at Module._compile (C:\Users\Mew\vimfiles\plugged\coc.nvim\build\index.js:78000:28)
    at Module._extensions..js (node:internal/modules/cjs/loader:1588:10)
    at Module.load (node:internal/modules/cjs/loader:1282:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\Mew\\AppData\\Local\\coc\\extensions\\node_modules\\coc-markdown-preview-enhanced\\lib\\index.js',
    'C:\\Users\\Mew\\AppData\\Local\\coc\\extensions\\node_modules\\coc-markdown-preview-enhanced\\lib\\index.js'
  ]
}
2024-07-21T09:27:46.290 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:27:50.987 ERROR (pid:32392) [timing] - activate coc-markdown-preview-enhanced timeout after 5000ms
2024-07-21T09:27:56.249 INFO (pid:32392) [attach] - receive notification: openLog []
2024-07-21T09:27:56.620 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:27:57.842 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:28:15.598 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:28:23.400 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:28:40.164 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:28:43.651 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:28:48.146 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:28:52.582 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:28:53.318 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:28:54.498 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:29:21.909 INFO (pid:32392) [attach] - Request action: extensionStats []
2024-07-21T09:29:29.176 INFO (pid:32392) [attach] - receive notification: uninstallExtension [ 'coc-markdown-preview-enhanced' ]
2024-07-21T09:29:29.502 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:29:35.199 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:30:11.624 INFO (pid:32392) [attach] - receive notification: installExtensions [ 'coc-markdown-preview-enhanced' ]
2024-07-21T09:30:11.660 INFO (pid:32392) [attach] - receive notification: doAutocmd [ 1, 7 ]
2024-07-21T09:30:11.961 INFO (pid:32392) [extension-installer] - Fetched info of coc-markdown-preview-enhanced {
  'dist.tarball': 'https://mirrors.huaweicloud.com/repository/npm/coc-markdown-preview-enhanced/-/coc-markdown-preview-enhanced-0.5.3.tgz',
  'engines.coc': '^0.0.80',
  version: '0.5.3',
  name: 'coc-markdown-preview-enhanced'
}
2024-07-21T09:30:12.061 INFO (pid:32392) [model-download] - Download completed: URL {
  href: 'https://mirrors.huaweicloud.com/repository/npm/coc-markdown-preview-enhanced/-/coc-markdown-preview-enhanced-0.5.3.tgz',
  origin: 'https://mirrors.huaweicloud.com',
  protocol: 'https:',
  username: '',
  password: '',
  host: 'mirrors.huaweicloud.com',
  hostname: 'mirrors.huaweicloud.com',
  port: '',
  pathname: '/repository/npm/coc-markdown-preview-enhanced/-/coc-markdown-preview-enhanced-0.5.3.tgz',
  search: '',
  searchParams: URLSearchParams {},
  hash: ''
}
2024-07-21T09:30:12.063 INFO (pid:32392) [model-download] - Downloaded https://mirrors.huaweicloud.com/repository/npm/coc-markdown-preview-enhanced/-/coc-markdown-preview-enhanced-0.5.3.tgz => C:\Users\Mew\AppData\Local\coc\extensions\node_modules\coc-markdown-preview-enhanced-24c169a0-0950-4d93-9b6e-5e71f9edf674
2024-07-21T09:30:12.149 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:30:20.953 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:30:53.395 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:30:54.059 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:30:54.617 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:32:45.657 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:32:46.609 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:33:01.075 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:33:04.284 INFO (pid:32392) [attach] - receive notification: doAutocmd [ 2, 7 ]
2024-07-21T09:33:04.629 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:33:09.580 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:33:10.869 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:33:11.268 INFO (pid:32392) [attach] - Request action: doKeymap [ 'coc-explorer-key-n-[cr]' ]
2024-07-21T09:33:11.616 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:33:13.133 INFO (pid:32392) [attach] - Request action: doKeymap [ 'coc-explorer-key-n-l' ]
2024-07-21T09:33:13.493 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:33:14.238 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:33:16.012 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:33:17.227 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:33:18.080 INFO (pid:32392) [attach] - Request action: doKeymap [ 'coc-explorer-key-n-[cr]' ]
2024-07-21T09:33:18.189 ERROR (pid:32392) [extensions-manager] - Error on active extension coc-markdown-preview-enhanced: Error: Cannot find module '@shd101wyy/mume'
Require stack:
- C:\Users\Mew\AppData\Local\coc\extensions\node_modules\coc-markdown-preview-enhanced\lib\index.js
- C:\Users\Mew\AppData\Local\coc\extensions\node_modules\coc-markdown-preview-enhanced\lib\index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1219:15)
    at Module._load (node:internal/modules/cjs/loader:1045:27)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:215:24)
    at Module.require (node:internal/modules/cjs/loader:1304:12)
    at req (C:\Users\Mew\vimfiles\plugged\coc.nvim\build\index.js:77984:17)
    at Object.<anonymous> (C:\Users\Mew\AppData\Local\coc\extensions\node_modules\coc-markdown-preview-enhanced\lib\index.js:262:20)
    at Module._compile (C:\Users\Mew\vimfiles\plugged\coc.nvim\build\index.js:78000:28)
    at Module._extensions..js (node:internal/modules/cjs/loader:1588:10)
    at Module.load (node:internal/modules/cjs/loader:1282:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\Mew\\AppData\\Local\\coc\\extensions\\node_modules\\coc-markdown-preview-enhanced\\lib\\index.js',
    'C:\\Users\\Mew\\AppData\\Local\\coc\\extensions\\node_modules\\coc-markdown-preview-enhanced\\lib\\index.js'
  ]
}
2024-07-21T09:33:18.189 ERROR (pid:32392) [server] - unhandledRejection  Promise {
  <rejected> Error: Cannot find module '@shd101wyy/mume'
  Require stack:
  - C:\Users\Mew\AppData\Local\coc\extensions\node_modules\coc-markdown-preview-enhanced\lib\index.js
  - C:\Users\Mew\AppData\Local\coc\extensions\node_modules\coc-markdown-preview-enhanced\lib\index.js
      at Module._resolveFilename (node:internal/modules/cjs/loader:1219:15)
      at Module._load (node:internal/modules/cjs/loader:1045:27)
      at TracingChannel.traceSync (node:diagnostics_channel:315:14)
      at wrapModuleLoad (node:internal/modules/cjs/loader:215:24)
      at Module.require (node:internal/modules/cjs/loader:1304:12)
      at req (C:\Users\Mew\vimfiles\plugged\coc.nvim\build\index.js:77984:17)
      at Object.<anonymous> (C:\Users\Mew\AppData\Local\coc\extensions\node_modules\coc-markdown-preview-enhanced\lib\index.js:262:20)
      at Module._compile (C:\Users\Mew\vimfiles\plugged\coc.nvim\build\index.js:78000:28)
      at Module._extensions..js (node:internal/modules/cjs/loader:1588:10)
      at Module.load (node:internal/modules/cjs/loader:1282:32) {
    code: 'MODULE_NOT_FOUND',
    requireStack: [
      'C:\\Users\\Mew\\AppData\\Local\\coc\\extensions\\node_modules\\coc-markdown-preview-enhanced\\lib\\index.js',
      'C:\\Users\\Mew\\AppData\\Local\\coc\\extensions\\node_modules\\coc-markdown-preview-enhanced\\lib\\index.js'
    ]
  }
} Error: Cannot find module '@shd101wyy/mume'
Require stack:
- C:\Users\Mew\AppData\Local\coc\extensions\node_modules\coc-markdown-preview-enhanced\lib\index.js
- C:\Users\Mew\AppData\Local\coc\extensions\node_modules\coc-markdown-preview-enhanced\lib\index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1219:15)
    at Module._load (node:internal/modules/cjs/loader:1045:27)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:215:24)
    at Module.require (node:internal/modules/cjs/loader:1304:12)
    at req (C:\Users\Mew\vimfiles\plugged\coc.nvim\build\index.js:77984:17)
    at Object.<anonymous> (C:\Users\Mew\AppData\Local\coc\extensions\node_modules\coc-markdown-preview-enhanced\lib\index.js:262:20)
    at Module._compile (C:\Users\Mew\vimfiles\plugged\coc.nvim\build\index.js:78000:28)
    at Module._extensions..js (node:internal/modules/cjs/loader:1588:10)
    at Module.load (node:internal/modules/cjs/loader:1282:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\Mew\\AppData\\Local\\coc\\extensions\\node_modules\\coc-markdown-preview-enhanced\\lib\\index.js',
    'C:\\Users\\Mew\\AppData\\Local\\coc\\extensions\\node_modules\\coc-markdown-preview-enhanced\\lib\\index.js'
  ]
}
2024-07-21T09:33:18.482 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:33:22.761 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:33:23.181 ERROR (pid:32392) [timing] - activate coc-markdown-preview-enhanced timeout after 5000ms
2024-07-21T09:33:29.585 INFO (pid:32392) [attach] - Request action: commandList [ '', 'CocCommand ', 11 ]
2024-07-21T09:33:47.119 INFO (pid:32392) [attach] - Request action: commandList [ 'ma', 'CocCommand ma', 13 ]
2024-07-21T09:33:47.547 INFO (pid:32392) [attach] - Request action: commandList [ 'ma', 'CocCommand ma', 13 ]
2024-07-21T09:33:54.192 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:33:58.702 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:33:59.150 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:34:03.276 INFO (pid:32392) [attach] - Request action: doKeymap [ 'coc-explorer-key-n-[cr]' ]
2024-07-21T09:34:03.712 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:34:04.970 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:34:06.156 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:34:06.401 INFO (pid:32392) [attach] - Request action: doKeymap [ 'coc-explorer-key-n-[cr]' ]
2024-07-21T09:34:06.931 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:34:10.120 INFO (pid:32392) [attach] - receive notification: runCommand [ 'explorer' ]
2024-07-21T09:34:10.446 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:34:11.643 INFO (pid:32392) [attach] - receive notification: runCommand [ 'explorer' ]
2024-07-21T09:34:12.299 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:34:14.270 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:34:14.947 INFO (pid:32392) [attach] - Request action: doKeymap [ 'coc-explorer-key-n-[cr]' ]
2024-07-21T09:34:15.389 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:34:16.258 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:34:17.021 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:34:21.602 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:34:22.839 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:34:25.897 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:34:31.606 INFO (pid:32392) [attach] - receive notification: openList []
2024-07-21T09:34:31.637 INFO (pid:32392) [attach] - receive notification: doAutocmd [ 1, 10 ]
2024-07-21T09:34:32.762 INFO (pid:32392) [attach] - receive notification: openList [ 'commands' ]
2024-07-21T09:34:32.795 INFO (pid:32392) [attach] - receive notification: doAutocmd [ 1, 11 ]
2024-07-21T09:34:36.370 ERROR (pid:32392) [events] - Error on event: InputChar Error: Command: markdown-preview-enhanced.openPreview not found
    at CommandManager.executeCommand (C:\Users\Mew\vimfiles\plugged\coc.nvim\build\index.js:27228:25)
    at CommandManager.fireCommand (C:\Users\Mew\vimfiles\plugged\coc.nvim\build\index.js:27237:30)
    at async Object.execute (C:\Users\Mew\vimfiles\plugged\coc.nvim\build\index.js:68682:11)
    at async ListSession.doItemAction (C:\Users\Mew\vimfiles\plugged\coc.nvim\build\index.js:68563:13)
    at async ListSession.doAction (C:\Users\Mew\vimfiles\plugged\coc.nvim\build\index.js:68292:27)
    at async ListManager.doAction (C:\Users\Mew\vimfiles\plugged\coc.nvim\build\index.js:76036:9)
    at async C:\Users\Mew\vimfiles\plugged\coc.nvim\build\index.js:66649:11
    at async Mappings.doAction (C:\Users\Mew\vimfiles\plugged\coc.nvim\build\index.js:66890:9)
    at async Mappings.doInsertKeymap (C:\Users\Mew\vimfiles\plugged\coc.nvim\build\index.js:66844:11)
    at async ListManager.onInsertInput (C:\Users\Mew\vimfiles\plugged\coc.nvim\build\index.js:76212:20)
2024-07-21T09:34:36.681 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:34:44.485 INFO (pid:32392) [attach] - receive notification: openLog []
2024-07-21T09:34:44.835 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:34:46.015 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:35:01.310 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:35:02.740 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:35:06.231 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:35:08.052 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:35:09.391 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:35:17.568 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:35:38.085 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:35:39.738 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:35:40.189 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:41:53.378 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:41:55.073 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:42:00.115 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:42:06.514 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:43:14.671 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:43:15.825 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:43:16.636 INFO (pid:32392) [attach] - receive notification: highlight []
2024-07-21T09:43:21.036 INFO (pid:32392) [attach] - receive notification: showInfo []

**Steps to reproduce**
1. execute `nvim`
2. `:CocCommand markdown-preview-enhanced.openPreview`
3. See error

**Expected behavior**

正常打开 markdown 文件的预览窗口或浏览页面

**Screenshots**

**Additional context**
None

**Comment by weirongxu** [comment]
应该是安装 npm 时的网络问题，切换 npm 镜像或者使用网络代理重新安装。
